package com.example.todo.mybatis.mapper;

import com.example.todo.mybatis.domain.TaskType;
import com.example.todo.mybatis.domain.TaskTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    long countByExample(TaskTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int deleteByExample(TaskTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int insert(TaskType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int insertSelective(TaskType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    List<TaskType> selectByExample(TaskTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    TaskType selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int updateByExampleSelective(@Param("record") TaskType record, @Param("example") TaskTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int updateByExample(@Param("record") TaskType record, @Param("example") TaskTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int updateByPrimaryKeySelective(TaskType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_type
     *
     * @mbg.generated Mon May 22 20:41:44 JST 2023
     */
    int updateByPrimaryKey(TaskType record);
}